---
- name: Check if version {{ rclone_version }} is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show rclone || true
  register: _dpkg_query
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ rclone_package_url }}"
    state: present
  when: _dpkg_query.stdout != rclone_version

- name: Configure Bash completion
  ansible.builtin.command: >
    rclone completion bash /etc/bash_completion.d/rclone
  when:
    - _dpkg_query.stdout != rclone_version
    - rclone_enable_bash_completion | bool
