---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: Install package
  ansible.builtin.apt:
    deb: "{{ rclone_package_url }}"
    state: present
  when: rclone_version != ansible_facts.packages["rclone"][0]["version"] | default("")

- name: Configure Bash completion
  ansible.builtin.command: >
    rclone completion bash /etc/bash_completion.d/rclone
  when:
    - rclone_version != ansible_facts.packages["rclone"][0]["version"] | default("")
    - rclone_enable_bash_completion | bool
