[tool.bumpversion]
current_version = "2025.01.0"
# Based on: https://callowayproject.github.io/bump-my-version/howtos/calver/
# Ref: https://regex101.com/r/l4ZMkR/1
parse = """
(?x)                     # Verbose mode
(?P<release>             # The release part
    (?:[1-9][0-9]{3})\\. # YYYY.
    (?:0[1-9]|1[0-2])    # 0M
)
(?:\\.(?P<patch>[0-9]+)) # .patch
"""
serialize = ["{release}.{patch}"]
commit = true
message = "chore: bump version to {new_version}"
tag = true
tag_name = "v{new_version}"
tag_message = "Version {new_version}"

[tool.bumpversion.parts.release]
calver_format = "{YYYY}.{0M}"

[[tool.bumpversion.files]]
filename = "VERSION"
