---
- name: Linux setup
  hosts: all
  gather_facts: "{{ not (skip_facts | default(false)) }}"

  module_defaults:
    ansible.builtin.setup:
      # Ohai is slow, so avoid using it
      gather_subset: "all,!ohai"

  vars_files:
    - config.default.yml
    - config.yml
    - vault.yml

  roles:
    # Base system & desktop
    - role: base-system
      tags: [base, base-system]
    - role: ubuntu-pro
      tags: [base, ubuntu-pro]
    - role: packages
      tags: [base, packages]
    - role: git
      tags: [base, git]
    - role: xubuntu-desktop
      tags: [base, xubuntu]
      when: configure_xubuntu_desktop
    - role: ulauncher
      tags: [base, ulauncher]
    - role: dotfiles
      tags: [base, dotfiles]

    # Backup
    - role: rclone
      tags: [backup, rclone]
      when: install_rclone
    - role: restic
      tags: [backup, restic]
    - role: resticprofile
      tags: [backup, resticprofile]
    - role: syncthing
      tags: [backup, syncthing]

    # Utilities
    - role: firefox
      tags: [utils, firefox]
    - role: chrome
      tags: [utils, chrome]
    - role: spotify
      tags: [utils, spotify]
    - role: steam
      tags: [utils, steam]
      when: install_steam

    # Chat
    - role: discord
      tags: [chat, discord]
    - role: slack
      tags: [chat, slack]

    # Infrastructure
    - role: geerlingguy.docker
      tags: [infra, docker]
    - role: cinc-workstation
      tags: [infra, cinc-workstation]
      when: install_cinc_workstation
    - role: kvm
      tags: [infra, kvm]
      when: install_kvm

    # Cloud tools
    - role: aws-cli
      tags: [cloud-tools, aws-cli]
    - role: session-manager-plugin
      tags: [cloud-tools, session-manager-plugin]
    - role: doppler
      tags: [cloud-tools, doppler]

    # Development
    - role: mise
      tags: [dev, mise]
    - role: bat
      tags: [dev, bat]
    - role: vscode
      tags: [dev, vscode]
    - role: q
      tags: [dev, q]
      when: install_q
