---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: Install package
  ansible.builtin.apt:
    deb: "{{ chrome_package_url }}"
    state: present
  when: "'google-chrome-stable' not in ansible_facts.packages"
