---
- name: Check if Chrome is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show google-chrome-stable || true
  register: _dpkg_query
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ chrome_package_url }}"
    state: present
  when: "'no packages found matching' in _dpkg_query.stderr"
