---
- name: Check if version {{ bat_version }} is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show bat || true
  register: _dpkg_query
  changed_when: false
  tags: bat:install

- name: Install package
  ansible.builtin.apt:
    deb: "{{ bat_package_url }}"
    state: present
    install_recommends: false
  when: _dpkg_query.stdout != bat_version
  tags: bat:install

- name: Disable package installation from Ubuntu repos
  ansible.builtin.copy:
    content: |
      # Managed by Ansible
      Package: bat
      Pin: release o=Ubuntu
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/bat
    owner: root
    group: root
    mode: "0644"
  tags: bat:install

- name: Ensure configuration directory exists
  ansible.builtin.file:
    path: "{{ bat_config_file | dirname }}"
    state: directory
    owner: "{{ bat_config_owner }}"
    group: "{{ bat_config_group }}"
    mode: "0755"
  when: bat_config_content != ""
  tags: bat:config

- name: Create configuration file
  ansible.builtin.copy:
    content: "{{ bat_config_content }}"
    dest: "{{ bat_config_file }}"
    owner: "{{ bat_config_owner }}"
    group: "{{ bat_config_group }}"
    mode: "{{ bat_config_mode }}"
  when: bat_config_content != ""
  tags: bat:config
