---
- name: Check if version {{ dive_version }} is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show dive || true
  register: _dpkg_query
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ dive_package_url }}"
    state: present
    install_recommends: false
  when: dive_version != _dpkg_query.stdout
