---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: Install package
  ansible.builtin.apt:
    deb: "{{ dive_package_url }}"
    state: present
  when: dive_version not in ansible_facts.packages["dive"] | default([]) | map(attribute="version")
