---
- name: Check if Steam is installed
  ansible.builtin.shell: dpkg-query --show steam-launcher || true
  register: _dpkg_query
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb
    state: present
    install_recommends: false
  when: "'no packages found matching' in _dpkg_query.stderr"
