---
- name: Check if Steam is installed
  ansible.builtin.shell: dpkg-query --show steam-launcher || true
  register: _dpkg_query
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ steam_package_url }}"
    state: present
  when: "'no packages found matching' in _dpkg_query.stderr"
