---
awsvault_version: 7.2.0

awsvault_dl_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

awsvault_archive_url: >-
  https://github.com/99designs/aws-vault/releases/download/v{{ awsvault_version }}/aws-vault-linux-{{ awsvault_dl_arch }}

awsvault_sha256sums_url: >-
  https://github.com/99designs/aws-vault/releases/download/v{{ awsvault_version }}/SHA256SUMS

awsvault_bin_path: /usr/local/bin/aws-vault

awsvault_completion_url: >-
  https://raw.githubusercontent.com/99designs/aws-vault/v{{ awsvault_version }}/contrib/completions/bash/aws-vault.bash

awsvault_configure_bash_completion: true
