---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: packages:apt:update

- name: Install APT packages
  ansible.builtin.apt:
    name: "{{ packages_apt_install }}"
    state: present
  tags: packages:apt:install

- name: Remove defined APT packages
  ansible.builtin.apt:
    name: "{{ packages_apt_remove }}"
    state: absent
    purge: "{{ packages_apt_purge }}"
  tags: packages:apt:remove

- name: Remove APT automatically installed packages that are no longer needed
  ansible.builtin.apt:
    autoremove: true
    purge: "{{ packages_apt_purge }}"
  when: packages_apt_autoremove | bool
  tags: packages:apt:autoremove

- name: Configure version pinnings
  ansible.builtin.template:
    src: apt/version-pinning.j2
    dest: /etc/apt/preferences.d/ansible-version-pinning
    owner: root
    group: root
    mode: "0644"
    lstrip_blocks: true
  when: packages_apt_pin_versions | length > 0

- name: Ensure version pinning configuration is absent
  ansible.builtin.file:
    path: /etc/apt/preferences.d/ansible-version-pinning
    state: absent
  when: packages_apt_pin_versions | length == 0
