---
- name: Check if pipx is installed
  ansible.builtin.shell: pipx --version || true
  register: _check_version
  changed_when: false
  tags: packages:pipx:setup

- name: Install pipx using pip
  ansible.builtin.pip:
    name: pipx
    version: "{{ packages_pipx_cli_version }}"
    state: present
    virtualenv: "{{ packages_pipx_cli_venv }}"
    virtualenv_command: python3 -m venv
  when: _check_version.stdout == ""
  tags: packages:pipx:setup

- name: Create global symlink to pipx CLI
  ansible.builtin.file:
    src: "{{ packages_pipx_cli_venv }}/bin/pipx"
    dest: /usr/local/bin/pipx
    owner: root
    group: root
    state: link
  when: _check_version.stdout == ""
  tags: packages:pipx:setup

- name: Install pipx user packages
  community.general.pipx:
    name: "{{ item.name | default(item) }}"
    source: "{{ item.source | default(omit) }}"
    state: "{{ item.state | default('install') }}"
    executable: pipx
  loop: "{{ packages_pipx_install_user }}"
  become: false
  tags: packages:pipx:user

- name: Install pipx global packages
  community.general.pipx:
    name: "{{ item.name | default(item) }}"
    source: "{{ item.source | default(omit) }}"
    state: "{{ item.state | default('install') }}"
    executable: pipx
    global: true
  loop: "{{ packages_pipx_install_global }}"
  register: _pipx_cmd
  changed_when: "'Not modifying' not in _pipx_cmd.stdout"
  tags: packages:pipx:global
