---
- name: Remove snapd package
  ansible.builtin.apt:
    name: snapd
    state: absent
    purge: true

- name: Configure APT to prevent snapd package installation
  ansible.builtin.copy:
    content: |
      # Managed by Ansible
      Package: snapd
      Pin: release *
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/snapd-disabled
    owner: root
    group: root
    mode: "0644"
