---
- name: Check if version {{ awsvault_version }} is installed
  ansible.builtin.shell: aws-vault --version || true
  register: _check_version
  changed_when: false

- name: Download and install binary
  ansible.builtin.get_url:
    url: "{{ awsvault_archive_url }}"
    dest: "{{ awsvault_bin_path }}"
    checksum: sha256:{{ awsvault_sha256sums_url }}
    owner: root
    group: root
    mode: "0755"
  when: '("v" + awsvault_version) not in _check_version.stderr'

- name: Download and install Bash completion file
  ansible.builtin.get_url:
    url: "{{ awsvault_completion_url }}"
    dest: /etc/bash_completion.d/aws-vault
    force: true
    owner: root
    group: root
    mode: "0644"
  when: awsvault_configure_bash_completion | bool
