---
- name: Check if version {{ zoom_version }} is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show zoom || true
  register: _dpkg_query
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ zoom_package_url }}"
    state: present
    install_recommends: false
  when: _dpkg_query.stdout != zoom_version
