---
- name: Install repository key
  ansible.builtin.get_url:
    url: "{{ syncthing_apt_repo_key_url }}"
    dest: "{{ syncthing_apt_repo_key_file }}"
    force: true
    owner: root
    group: root
    mode: "0644"
  tags:
    - syncthing:repo
    - syncthing:install

- name: Ensure unused repository channels are absent
  ansible.builtin.apt_repository:
    repo: "{{ syncthing_apt_repo_base }} {{ item }}"
    filename: "{{ syncthing_apt_repo_file }}"
    state: absent
  loop: "{{ ['stable', 'stable-v2', 'candidate'] | difference([syncthing_apt_repo_channel]) }}"
  tags:
    - syncthing:repo
    - syncthing:install

- name: Configure repository
  ansible.builtin.apt_repository:
    repo: "{{ syncthing_apt_repo_base }} {{ syncthing_apt_repo_channel }}"
    filename: "{{ syncthing_apt_repo_file }}"
    state: present
    update_cache: true
  tags:
    - syncthing:repo
    - syncthing:install

- name: Install packages
  ansible.builtin.apt:
    name: syncthing
    state: present
  tags: syncthing:install

- name: Enable and run systemd service (user level)
  ansible.builtin.systemd_service:
    name: syncthing
    state: started
    enabled: true
    scope: user
  become: false
  when:
    - syncthing_enable_user_service | bool
    - ansible_facts.service_mgr == "systemd"
    - ansible_facts.user_id != "root"
  tags: syncthing:service
