---
- name: Check if MEGASync is installed
  ansible.builtin.shell: dpkg-query --show megasync || true
  register: _dpkg_query
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ megasync_package_url }}"
    state: present
  when: "'no packages found' in _dpkg_query.stderr"
