---
asdf_version: 0.18.0

asdf_dl_arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"

asdf_dl_url: >-
  https://github.com/asdf-vm/asdf/releases/download/v{{ asdf_version }}/asdf-v{{ asdf_version }}-linux-{{ asdf_dl_arch }}.tar.gz

asdf_install_path: ~/.local/bin/asdf
asdf_install_become: false

asdf_configure_bashrc: true
asdf_bashrc_file: ~/.bashrc
asdf_bashrc_become: false

asdf_configure_bash_completion: true
