---
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"

- name: Install repository key
  ansible.builtin.get_url:
    url: "{{ mise_apt_repo_key_url }}"
    dest: "{{ mise_apt_repo_key_file }}"
    force: true
    owner: root
    group: root
    mode: "0644"

- name: Configure repository
  ansible.builtin.deb822_repository:
    name: mise
    types: deb
    uris: "{{ mise_apt_repo_uri }}"
    suites: "{{ mise_apt_repo_suite }}"
    components: "{{ mise_apt_repo_component }}"
    signed_by: "{{ mise_apt_repo_key_file }}"
    state: present
  notify: mise - apt update

- name: Flush handlers to update the APT cache
  ansible.builtin.meta: flush_handlers

- name: Install package
  ansible.builtin.apt:
    name: mise
    state: present

- name: Configure .bashrc
  ansible.builtin.blockinfile:
    path: "{{ mise_bashrc_file | expanduser }}"
    marker: "### {mark} Managed by Ansible ###"
    block: |
      {{ mise_pre_activate_commands }}

      eval "$( {{ mise_activate_command }} )"
    create: true
    backup: false
    state: "{{ mise_configure_bashrc | bool | ternary('present', 'absent') }}"
  become: "{{ mise_bashrc_become }}"

- name: Install usage tool
  ansible.builtin.command: >
    mise use --global usage
  register: _install_usage
  changed_when: "'Installed' in _install_usage.stdout"
  when:
    - mise_configure_bashrc | bool
    - mise_configure_bash_completion | bool

- name: Configure Bash completion
  ansible.builtin.shell: >
    mise completion bash --include-bash-completion-lib > /etc/bash_completion.d/mise
  changed_when: false
  when:
    - mise_configure_bashrc | bool
    - mise_configure_bash_completion | bool
