---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: Run installation tasks
  when: discord_version not in ansible_facts.packages["discord"] | default([]) | map(attribute="version")
  block:
    - name: Fetch Discord download URL
      ansible.builtin.uri:
        url: https://discord.com/api/download?platform=linux
        method: HEAD
      register: _api_uri
      until: _api_uri.status == 200
      retries: 2
      delay: 3

    - name: Set package URL for the provided version
      ansible.builtin.set_fact:
        # (Hacky) way to reuse Discord's download URL structure
        discord_package_url: "{{ _api_uri.url | regex_replace('[0-9]+\\.[0-9]+\\.[0-9]+', discord_version) }}"
      when: discord_version != "latest"

    - name: Set variables for the latest version
      ansible.builtin.set_fact:
        discord_version: "{{ _api_uri.url | regex_replace('.*discord-(.+)\\.deb.*', '\\1') }}"
        discord_package_url: "{{ _api_uri.url }}"
      when: discord_version == "latest"

    - name: Install package
      ansible.builtin.apt:
        deb: "{{ discord_package_url }}"
        state: present
