---
- name: Check if version {{ discord_version }} is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show discord || true
  register: _dpkg_query
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ discord_package_url }}"
    state: present
    install_recommends: false
  when: _dpkg_query.stdout != discord_version
