---
- name: Fetch AWS CLI tags
  ansible.builtin.uri:
    url: https://api.github.com/repos/aws/aws-cli/tags
    return_content: true
  register: _fetch_tags
  when: awscli_version == "latest"

- name: Update version variable with the latest version
  ansible.builtin.set_fact:
    awscli_version: "{{ _fetch_tags.json[0].name }}"
  when: awscli_version == "latest"

- name: Check if version {{ awscli_version }} is installed
  ansible.builtin.shell: >
    {{ awscli_bin_dir }}/aws --version || true
  register: _check_version
  changed_when: false

- name: Download and install
  when:
    - ("aws-cli/" + awscli_version + " ") not in _check_version.stdout
  block:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: ansible-aws-cli-
      register: _temp_dir

    - name: Download and extract archive to temporary directory
      ansible.builtin.unarchive:
        remote_src: true
        src: https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_facts.architecture }}-{{ awscli_version }}.zip
        dest: "{{ _temp_dir.path }}"

    - name: Run installer
      ansible.builtin.command: >
        {{ _temp_dir.path }}/aws/install --bin-dir {{ awscli_bin_dir }} --install-dir {{ awscli_install_dir }} --update

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ _temp_dir.path }}"
        state: absent
