---
- name: Check if version {{ awscli_version }} is installed
  ansible.builtin.shell: >
    {{ awscli_bin_dir }}/aws --version || true
  register: _check_version
  changed_when: false

- name: Download and install
  when:
    - ("aws-cli/" + awscli_version + " ") not in _check_version.stdout
  block:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: ansible-aws-cli-
      register: _temp_dir

    - name: Download and extract archive to temporary directory
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ awscli_dl_url }}"
        dest: "{{ _temp_dir.path }}"

    - name: Run installer
      ansible.builtin.command: >
        {{ _temp_dir.path }}/aws/install --bin-dir {{ awscli_bin_dir }} --install-dir {{ awscli_install_dir }} --update

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ _temp_dir.path }}"
        state: absent
