---
# APT
packages_apt_install:
  # Base
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - dkms
  - exo-utils
  - tmux
  - tree
  - wget
  - xfce4-terminal
  # Password management
  - keepassxc
  - makepasswd
  - pwgen
  - seahorse
  # Development
  - gedit
  - gedit-plugins
  - jq
  - vim
  # Development/Python
  - libbz2-dev
  - libffi-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - python3-dev
  - python3-venv
  - zlib1g-dev
  # Sysadmin
  - arping
  - cifs-utils
  - conntrack
  - ethtool
  - gdebi-core
  - gnome-disk-utility
  - cracklib-runtime
  - exfat-fuse
  - exfatprogs
  - htop
  - iotop
  - iptraf-ng
  - lm-sensors
  - lshw
  - lsof
  - mtr-tiny
  - netcat-openbsd
  - network-manager-openvpn
  - network-manager-openvpn-gnome
  - nmap
  - openssh-client
  - rsync
  - traceroute
  - whois
  # Media
  - flameshot
  - fonts-dejavu
  - fonts-dejavu-extra
  - fonts-firacode
  - fonts-inconsolata
  - fonts-liberation
  - fonts-liberation2
  - fonts-noto-color-emoji
  - gimp
  - gpick
  - graphviz
  - peek
  - ristretto
  - shotwell
  - vlc
  - vlc-plugin-notify
  # Utilities
  - ack
  - atool
  - atril
  - mate-calc
  - dconf-editor
  - dos2unix
  - engrampa
  - gvfs-backends
  - ipcalc-ng
  - moreutils
  - multitail
  - p7zip-full
  - p7zip-rar
  - pbzip2
  - pigz
  - printer-driver-cups-pdf
  - rename
  - sqlite3
  - transmission-gtk
  - unar
  - unrar
  - unzip
  - wmctrl
  - xclip
  - xdotool
  - xz-utils
  - zenity

packages_apt_remove:
  - gnumeric
  - mousepad
  - command-not-found
  - gnome-software
  - gnome-software-common
  - gnome-software-plugin-snap
  - hexchat
  - motd-news-config
  - pidgin
  - pidgin-otr
  - sgt-launcher
  - sgt-puzzles
  - thunderbird
  - unattended-upgrades
  - xul-ext-ubufox

packages_apt_autoremove: true

# snap
packages_snap_disable_snapd: true

# pipx
packages_pipx_install:
  - bump-my-version
  - bump2version
  - cookiecutter
  - copier
  - name: pre-commit
    state: upgrade
  - name: ps-mem
    global: true
