---
# Autostart
xubuntu_autostart_disable_apps:
  - blueman
  - update-notifier

# XDG user dirs
xubuntu_xdg_documents_dir: library/Documents
xubuntu_xdg_download_dir: cache
xubuntu_xdg_music_dir: library/Music
xubuntu_xdg_pictures_dir: library/Pictures
xubuntu_xdg_publicshare_dir: library/Public
xubuntu_xdg_templates_dir: library/Templates
xubuntu_xdg_videos_dir: library/Videos

# Bookmarks
xubuntu_bookmarks:
  - /arquivos
  - ~/{{ xubuntu_xdg_download_dir }}
  - ~/projects

# Keyboard shortcuts
# Note: <Primary> means <Ctrl>
xubuntu_remove_command_shortcuts:
  - <Alt>F1
  - <Alt>F3
  - <Alt>Print
  - <Primary>Escape
  - <Primary><Alt>t
  - <Primary><Alt>Escape
  - <Super>f
  - XF86Messenger

xubuntu_command_shortcuts:
  # Audio
  - shortcut: <Primary><Super>Down
    cmd: amixer -q -M -D pulse sset Master 5%-
  - shortcut: <Primary><Super>Up
    cmd: amixer -q -M -D pulse sset Master 5%+
  # Spotify
  - shortcut: XF86Music
    cmd: spotify
  - shortcut: <Super>r
    cmd: spotify
  # Screenshot
  - shortcut: Print
    cmd: xfce4-screenshooter -f
  - shortcut: <Shift>Print
    cmd: xfce4-screenshooter -w
  - shortcut: <Super>Print
    cmd: flameshot gui
  # User session
  - shortcut: <Primary><Alt>Delete
    cmd: xfce4-session-logout
  - shortcut: <Primary><Alt>l
    cmd: xflock4
  # Window Manager
  - shortcut: <Primary><Alt>Left
    cmd: move-to-next-monitor
  - shortcut: <Primary><Alt>Right
    cmd: move-to-next-monitor
  # Xfce tools
  - shortcut: <Super>F1
    cmd: xfce4-find-cursor
  - shortcut: <Super>p
    cmd: xfce4-display-settings --minimal
  - shortcut: <Super>z
    cmd: xfce4-popup-applicationsmenu
  # Terminal
  - shortcut: <Super>Return
    cmd: xfce4-terminal --maximize
  - shortcut: <Super>KP_Enter
    cmd: xfce4-terminal --maximize
  # Utilities
  - shortcut: <Super>e
    cmd: exo-open --launch FileManager
  - shortcut: <Super>k
    cmd: keepassxc
  - shortcut: <Super>n
    cmd: code {{ xubuntu_home_dir }}/notes
  - shortcut: <Super>t
    cmd: exo-open --launch TerminalEmulator
  - shortcut: <Super>w
    cmd: sensible-browser https://keep.google.com

xubuntu_remove_window_manager_shortcuts:
  - <Alt>F7
  - <Alt>F9
  - <Primary>F1
  - <Primary>F2
  - <Primary>F3
  - <Primary>F4
  - <Primary>F5
  - <Primary>F6
  - <Primary>F7
  - <Primary>F8
  - <Primary>F9
  - <Primary>F10
  - <Primary>F11
  - <Primary>F12
  - <Primary><Alt>Up
  - <Primary><Alt>Down
  - <Primary><Alt>Left
  - <Primary><Alt>Right

xubuntu_window_manager_shortcuts:
  - shortcut: <Super>s
    cmd: hide_window_key
  - shortcut: <Super>Up
    cmd: maximize_window_key

# Theme
xubuntu_theme_packages:
  - greybird-gtk-theme
  - oxygen-cursor-theme

xubuntu_system_theme: Greybird-dark
xubuntu_cursor_theme: oxy-zion

# Fonts
xubuntu_fonts_apt_packages:
  - fonts-dejavu-core
  - fonts-noto-core
  - fonts-noto-mono

xubuntu_fonts_archives:
  - name: JetBrainsMono
    url: https://github.com/JetBrains/JetBrainsMono/releases/download/v2.304/JetBrainsMono-2.304.zip
    include_files:
      - fonts/*

xubuntu_system_default_font: Noto Sans 9
xubuntu_system_monospace_font: DejaVu Sans Mono 10
xubuntu_window_title_font: Noto Sans Bold 9

# Thunar
xubuntu_thunar_settings:
  - property: /last-location-bar
    value: ThunarLocationButtons
    value_type: string
  - property: /last-menubar-visible
    value: "false"
    value_type: bool
  - property: /last-restore-tabs
    value: "false"
    value_type: bool
  - property: /last-sort-column
    value: THUNAR_COLUMN_NAME
    value_type: string
  - property: /last-sort-order
    value: GTK_SORT_ASCENDING
    value_type: string
  - property: /last-view
    value: ThunarDetailsView
    value_type: string
  - property: /last-window-maximized
    value: "true"
    value_type: bool
  - property: /misc-change-window-icon
    value: "true"
    value_type: bool
  - property: /misc-confirm-close-multiple-tabs
    value: "false"
    value_type: bool
  - property: /misc-date-style
    value: THUNAR_DATE_STYLE_LONG
    value_type: string
  - property: /misc-full-path-in-title
    value: "false"
    value_type: bool
  - property: /misc-open-new-window-as-tab
    value: "true"
    value_type: bool
  - property: /misc-thumbnail-mode
    value: THUNAR_THUMBNAIL_MODE_ONLY_LOCAL
    value_type: string
  - property: /misc-folders-first
    value: "true"
    value_type: bool
  - property: /misc-volume-management
    value: "false"
    value_type: bool
  - property: /shortcuts-icon-size
    value: THUNAR_ICON_SIZE_24
    value_type: string

# Xfconf
xubuntu_xfconf_settings:
  # Desktop
  - channel: xfce4-desktop
    property: /desktop-icons/style
    value: "0"
    value_type: int
  - channel: xfce4-desktop
    property: /desktop-menu/show
    value: "true"
    value_type: bool
  - channel: xfce4-desktop
    property: /desktop-menu/show-icons
    value: "true"
    value_type: bool
  - channel: xfce4-desktop
    property: /windowlist-menu/show
    value: "false"
    value_type: bool
  # Window Manager
  - channel: xfwm4
    property: /general/button_layout
    value: CMH|O
    value_type: string

# Default apps
xubuntu_default_web_browser: firefox
