---
kvm_install_server_packages: true

kvm_server_packages:
  - bridge-utils
  - libvirt-clients
  - libvirt-daemon-system
  - qemu-kvm

kvm_install_virt_manager: false

kvm_virt_manager_packages:
  - virt-manager
  - gir1.2-spiceclientgtk-3.0
  - ssh-askpass-gnome

kvm_install_client_utilities: false

kvm_client_utilities_packages:
  # Provides 'cloud-localds'[1], which is useful to create a disk to use cloud-init + nocloud datasource
  # Ref: https://github.com/canonical/cloud-utils?tab=readme-ov-file#usage
  - cloud-image-utils
  # Provides 'mkisofs', which is used by e.g. the 'libvirt_cloudinit_disk' Terraform resource
  # Ref: https://registry.terraform.io/providers/dmacvicar/libvirt/latest/docs/resources/cloudinit
  - genisoimage

kvm_system_groups:
  # Allow using Packer's QEMU builder as a regular user
  # Ref: https://developer.hashicorp.com/packer/integrations/hashicorp/qemu/latest/components/builder/qemu
  - kvm
  # Allow using 'virsh' as a regular user
  - libvirt

kvm_users: []

kvm_disable_libvirt_qemu_security_driver: false
