---
- name: Set variable with expanded path
  ansible.builtin.set_fact:
    _opencode_install_path: "{{ opencode_install_path | expanduser }}"

- name: Fetch latest release from GitHub
  ansible.builtin.uri:
    url: https://api.github.com/repos/anomalyco/opencode/releases/latest
    headers:
      Accept: application/vnd.github+json
  register: _gh_release
  when: opencode_version == "latest"

- name: Set target version
  ansible.builtin.set_fact:
    _target_version: "{{ opencode_version if opencode_version != 'latest' else (_gh_release.json.tag_name | regex_replace('^v', '')) }}"

- name: Set target URL
  ansible.builtin.set_fact:
    # yamllint disable-line rule:line-length
    _target_url: https://github.com/anomalyco/opencode/releases/download/v{{ _target_version }}/opencode-linux-{{ opencode_dl_arch }}.tar.gz

- name: Check if version {{ _target_version }} is installed
  ansible.builtin.command: >
    {{ _opencode_install_path }} --version
  register: _check_version
  changed_when: false
  failed_when: false
  become: "{{ opencode_install_become }}"

- name: Ensure bin directory exists
  ansible.builtin.file:
    path: "{{ _opencode_install_path | dirname }}"
    state: directory
    mode: "0755"
  become: "{{ opencode_install_become }}"
  when: _check_version.rc != 0 or _target_version not in _check_version.stdout

- name: Install binary
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ _target_url }}"
    dest: "{{ opencode_install_path | dirname }}"
    include:
      - opencode
    mode: "0755"
  become: "{{ opencode_install_become }}"
  when:
    - not ansible_check_mode
    - _check_version.rc != 0 or _target_version not in _check_version.stdout

- name: Create symlink to binary
  ansible.builtin.file:
    src: "{{ opencode_install_path }}"
    dest: "{{ opencode_symlink_path | expanduser }}"
    state: link
  become: "{{ opencode_install_become }}"
  when: opencode_symlink_path != ""
