---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts['packages'] is not defined

- name: Install package
  ansible.builtin.apt:
    deb: "{{ ghostty_pkg_url }}"
    state: present
  when: ghostty_pkg_version not in ansible_facts['packages']['ghostty'] | default([]) | map(attribute="version")

- name: Ensure configuration directory exists
  ansible.builtin.file:
    path: "{{ ghostty_config_file | expanduser | dirname }}"
    state: directory
    mode: "0755"
  become: "{{ ghostty_config_become }}"
  when: ghostty_config_content != ""

- name: Create configuration file
  ansible.builtin.copy:
    content: "{{ ghostty_config_content }}"
    dest: "{{ ghostty_config_file }}"
    mode: "{{ ghostty_config_mode }}"
  become: "{{ ghostty_config_become }}"
  when: ghostty_config_content != ""
