---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: Install package
  ansible.builtin.apt:
    deb: "{{ q_package_url }}"
    state: present
  when: q_version != ansible_facts.packages["q-text-as-data"][0]["version"] | default("")
