---
- name: Check if version {{ q_version }} is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show q-text-as-data || true
  register: _dpkg_query
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ q_package_url }}"
    state: present
  when: _dpkg_query.stdout != q_version
