---
- name: Check if version {{ resticprofile_version }} is installed
  ansible.builtin.shell: >
    {{ resticprofile_bin_path }} version || true
  register: _check_version
  changed_when: false

- name: Install binary
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ resticprofile_dl_url }}"
    dest: "{{ resticprofile_bin_path | dirname }}"
    include:
      - resticprofile  # Extract only the binary
    owner: root
    group: root
    mode: "0755"
  when:
    - ("version " + resticprofile_version + " commit") not in _check_version.stdout

- name: Create symlink to binary
  ansible.builtin.file:
    src: "{{ resticprofile_bin_path }}"
    dest: "{{ resticprofile_bin_path | dirname }}/{{ resticprofile_symlink_name }}"
    owner: root
    group: root
    state: link
  when: resticprofile_symlink_name != ""
