---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: Install package
  ansible.builtin.apt:
    deb: "{{ granted_package_url }}"
    state: present
  when: granted_version not in ansible_facts.packages["granted"] | default([]) | map(attribute="version")
