---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: Install package
  ansible.builtin.apt:
    deb: "{{ granted_package_url }}"
    state: present
  when: granted_version != ansible_facts.packages["granted"][0]["version"] | default("")
