---
# For keyboard shortcuts, see 'keyboard-shortcuts.yml'

# Global

xubuntu_home_dir: "{{ '~' | expanduser }}"
xubuntu_config_dir: "{{ xubuntu_home_dir }}/.config"

# Autostart

xubuntu_autostart_dir: "{{ xubuntu_config_dir }}/autostart"

xubuntu_autostart_disable_apps:
  - blueman
  - update-notifier

# User dirs

xubuntu_user_dirs_base_dir: "{{ xubuntu_home_dir }}"

xubuntu_user_dirs:
  - name: DESKTOP
    path: Desktop
  - name: DOWNLOAD
    path: cache
  - name: TEMPLATES
    path: library/Templates
  - name: PUBLICSHARE
    path: library/Public
  - name: DOCUMENTS
    path: library/Documents
  - name: MUSIC
    path: library/Music
  - name: PICTURES
    path: library/Pictures
  - name: VIDEOS
    path: library/Videos

xubuntu_remove_default_user_dirs: false

# Bookmarks

xubuntu_bookmarks_file: "{{ xubuntu_config_dir }}/gtk-3.0/bookmarks"

xubuntu_bookmarks:
  - /arquivos
  - "{{ xubuntu_home_dir }}/cache"
  - "{{ xubuntu_home_dir }}/projects"

# Thunar

xubuntu_thunar_settings:
  - property: /last-location-bar
    value: ThunarLocationButtons
    value_type: string
  - property: /last-menubar-visible
    value: "false"
    value_type: bool
  - property: /last-restore-tabs
    value: "false"
    value_type: bool
  - property: /last-sort-column
    value: THUNAR_COLUMN_NAME
    value_type: string
  - property: /last-sort-order
    value: GTK_SORT_ASCENDING
    value_type: string
  - property: /last-view
    value: ThunarDetailsView
    value_type: string
  - property: /last-window-maximized
    value: "true"
    value_type: bool
  - property: /misc-change-window-icon
    value: "true"
    value_type: bool
  - property: /misc-confirm-close-multiple-tabs
    value: "false"
    value_type: bool
  - property: /misc-date-style
    value: THUNAR_DATE_STYLE_LONG
    value_type: string
  - property: /misc-full-path-in-title
    value: "false"
    value_type: bool
  - property: /misc-open-new-window-as-tab
    value: "true"
    value_type: bool
  - property: /misc-thumbnail-mode
    value: THUNAR_THUMBNAIL_MODE_ONLY_LOCAL
    value_type: string
  - property: /misc-folders-first
    value: "true"
    value_type: bool
  - property: /misc-volume-management
    value: "false"
    value_type: bool
  - property: /shortcuts-icon-size
    value: THUNAR_ICON_SIZE_24
    value_type: string

# Xfconf (misc)

xubuntu_xfconf_settings:
  # Desktop
  - channel: xfce4-desktop
    property: /desktop-icons/style
    value: "0"
    value_type: int
  - channel: xfce4-desktop
    property: /desktop-menu/show
    value: "true"
    value_type: bool
  - channel: xfce4-desktop
    property: /desktop-menu/show-icons
    value: "true"
    value_type: bool
  - channel: xfce4-desktop
    property: /windowlist-menu/show
    value: "false"
    value_type: bool

  # Window Manager
  - channel: xfwm4
    property: /general/button_layout
    value: CMH|O
    value_type: string

# System and cursor theme

xubuntu_theme_packages: []

xubuntu_system_theme: ""
xubuntu_cursor_theme: ""

# System fonts

xubuntu_fonts_packages: []

xubuntu_system_default_font: ""
xubuntu_system_monospace_font: ""
xubuntu_window_title_font: ""

# Default applications

xubuntu_default_web_browser: ""
xubuntu_default_file_manager: ""
xubuntu_default_mail_reader: ""
xubuntu_default_terminal_emulator: ""
