---
opencode_version: latest  # or specific version, e.g. '1.17.9'

opencode_dl_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'x64' }}"

opencode_install_path: ~/.opencode/bin/opencode
opencode_install_become: false

opencode_symlink_path: ~/.local/bin/opencode
