---
- name: Create autostart directory
  ansible.builtin.file:
    path: "{{ desktop_autostart_dir }}"
    state: directory

- name: Disable autostart of selected applications
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Hidden=true
    dest: "{{ desktop_autostart_dir }}/{{ item }}.desktop"
  loop: "{{ desktop_autostart_disable_apps }}"
