---
- name: Ensure bookmarks directory exist
  ansible.builtin.file:
    path: "{{ xubuntu_bookmarks_file | dirname }}"
    state: directory

- name: Configure bookmarks
  ansible.builtin.template:
    src: gtk-3.0-bookmarks.j2
    dest: "{{ xubuntu_bookmarks_file }}"
    lstrip_blocks: true
