---
- name: Install font packages
  ansible.builtin.apt:
    name: "{{ xubuntu_fonts_packages }}"
    state: present

- name: Ensure local font folders exist
  ansible.builtin.file:
    path: "{{ xubuntu_local_fonts_dir }}/{{ item.name }}"
    state: directory
  loop: "{{ xubuntu_extra_fonts }}"
  become: false

- name: Download and extract font archives
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ item.archive_url }}"
    dest: "{{ xubuntu_local_fonts_dir }}/{{ item.name }}"
    include: "{{ item.archive_files | default(omit) }}"
  loop: "{{ xubuntu_extra_fonts }}"
  notify: Rebuild fonts cache
  when: not ansible_check_mode
  become: false

- name: Ensure the fonts cache is updated
  ansible.builtin.meta: flush_handlers

- name: Configure system fonts
  community.general.xfconf:
    channel: "{{ item.channel }}"
    property: "{{ item.property }}"
    value: "{{ item.value }}"
    value_type: string
    state: present
  loop:
    - channel: xsettings
      property: /Gtk/FontName
      value: "{{ xubuntu_system_default_font }}"
    - channel: xsettings
      property: /Gtk/MonospaceFontName
      value: "{{ xubuntu_system_monospace_font }}"
    - channel: xfwm4
      property: /general/title_font
      value: "{{ xubuntu_window_title_font }}"
  when: item.value != ""
  become: false
