---
- name: Remove keyboard shortcuts (commands)
  community.general.xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /commands/custom/{{ item }}
    state: absent
  loop: "{{ xubuntu_remove_command_shortcuts }}"
  tags: xubuntu:keyboard-shortcuts:commands

- name: Remove keyboard shortcuts (xfwm4)
  community.general.xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/{{ item }}
    state: absent
  loop: "{{ xubuntu_remove_window_manager_shortcuts }}"
  tags: xubuntu:keyboard-shortcuts:xfwm4

- name: Configure keyboard shortcuts (commands)
  community.general.xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /commands/custom/{{ item.shortcut }}
    value: "{{ item.cmd }}"
    value_type: string
    state: present
  loop: "{{ xubuntu_command_shortcuts }}"
  loop_control:
    label: "{{ item.shortcut }} - {{ item.cmd }}"
  when: item.shortcut not in xubuntu_remove_command_shortcuts
  tags: xubuntu:keyboard-shortcuts:commands

- name: Configure keyboard shortcuts (xfwm4)
  community.general.xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /xfwm4/custom/{{ item.shortcut }}
    value: "{{ item.cmd }}"
    value_type: string
    state: present
  loop: "{{ xubuntu_window_manager_shortcuts }}"
  loop_control:
    label: "{{ item.shortcut }} - {{ item.cmd }}"
  when: item.shortcut not in xubuntu_remove_window_manager_shortcuts
  tags: xubuntu:keyboard-shortcuts:xfwm4
