---
- name: Include autostart tasks
  ansible.builtin.import_tasks: autostart.yml
  become: false
  tags: xubuntu:autostart

- name: Include user dirs tasks
  ansible.builtin.import_tasks: user-dirs.yml
  become: false
  tags: xubuntu:user-dirs

- name: Include bookmark tasks
  ansible.builtin.import_tasks: bookmarks.yml
  become: false
  tags: xubuntu:bookmarks

- name: Include keyboard shortcuts tasks
  ansible.builtin.import_tasks: keyboard-shortcuts.yml
  become: false
  tags: xubuntu:keyboard-shortcuts

- name: Include theme tasks
  ansible.builtin.import_tasks: theme.yml
  tags: xubuntu:theme

- name: Include fonts tasks
  ansible.builtin.import_tasks: fonts.yml
  tags: xubuntu:fonts

- name: Apply Thunar settings
  community.general.xfconf:
    channel: thunar
    property: "{{ item.property }}"
    value: "{{ item.value }}"
    value_type: "{{ item.value_type }}"
    state: present
  loop: "{{ xubuntu_thunar_settings }}"
  loop_control:
    label: "{{ item.property }} - {{ item.value }}"
  become: false
  tags: xubuntu:thunar

- name: Apply Xfconf settings
  community.general.xfconf:
    channel: "{{ item.channel }}"
    property: "{{ item.property }}"
    value: "{{ item.value }}"
    value_type: "{{ item.value_type }}"
    state: present
  loop: "{{ xubuntu_xfconf_settings }}"
  loop_control:
    label: "{{ item.property }} - {{ item.value }}"
  become: false
  tags: xubuntu:xfconf

- name: Configure Xfce default applications
  ansible.builtin.template:
    src: xfce4/helpers.rc.j2
    dest: "{{ xubuntu_config_dir }}/xfce4/helpers.rc"
    lstrip_blocks: true
  become: false
  tags: xubuntu:default-apps
