---
- name: Include autostart tasks
  ansible.builtin.import_tasks: autostart.yml
  tags: xubuntu-desktop:autostart

- name: Include user dir tasks
  ansible.builtin.import_tasks: user-dirs.yml
  tags: xubuntu-desktop:user-dirs

- name: Include bookmark tasks
  ansible.builtin.import_tasks: bookmarks.yml
  tags: xubuntu-desktop:bookmarks

- name: Include keyboard shortcuts tasks
  ansible.builtin.import_tasks: keyboard-shortcuts.yml
  become: true
  become_user: "{{ desktop_user }}"
  tags: xubuntu-desktop:keyboard-shortcuts

- name: Include theme tasks
  ansible.builtin.import_tasks: theme.yml
  tags: xubuntu-desktop:theme

- name: Apply Thunar settings
  community.general.xfconf:
    channel: thunar
    property: "{{ item.property }}"
    value: "{{ item.value }}"
    value_type: "{{ item.value_type }}"
    state: present
  loop: "{{ desktop_thunar_settings }}"
  loop_control:
    label: "{{ item.property }} - {{ item.value }}"
  become: true
  become_user: "{{ desktop_user }}"
  tags: xubuntu-desktop:thunar

- name: Apply Xfconf settings
  community.general.xfconf:
    channel: "{{ item.channel }}"
    property: "{{ item.property }}"
    value: "{{ item.value }}"
    value_type: "{{ item.value_type }}"
    state: present
  loop: "{{ desktop_xfconf_settings }}"
  loop_control:
    label: "{{ item.property }} - {{ item.value }}"
  become: true
  become_user: "{{ desktop_user }}"
  tags: xubuntu-desktop:xfconf

- name: Configure Xfce default applications
  ansible.builtin.template:
    src: xfce4/helpers.rc.j2
    dest: "{{ desktop_config_dir }}/xfce4/helpers.rc"
    owner: "{{ desktop_user }}"
    group: "{{ desktop_user }}"
    lstrip_blocks: true
  tags: xubuntu-desktop:default-apps
