---
- name: Install theme packages
  ansible.builtin.package:
    name: "{{ xubuntu_theme_packages }}"
    state: present

- name: Configure system theme
  community.general.xfconf:
    channel: "{{ item.channel }}"
    property: "{{ item.property }}"
    value: "{{ xubuntu_system_theme }}"
    value_type: string
    state: present
  loop:
    - channel: xsettings
      property: /Net/ThemeName
    - channel: xfwm4
      property: /general/theme
  when: xubuntu_system_theme != ""
  become: false

- name: Configure cursor theme (alternatives)
  community.general.alternatives:
    name: x-cursor-theme
    path: /etc/X11/cursors/{{ xubuntu_cursor_theme }}.theme
  when: xubuntu_cursor_theme != ""

- name: Configure cursor theme (xfconf/xsettings)
  community.general.xfconf:
    channel: xsettings
    property: /Gtk/CursorThemeName
    value: "{{ xubuntu_cursor_theme }}"
    value_type: string
    state: present
  when: xubuntu_cursor_theme != ""
  become: false
