---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: Install package
  ansible.builtin.apt:
    deb: "{{ ulauncher_package_url }}"
    state: present
  when: ulauncher_version != ansible_facts.packages["ulauncher"][0]["version"] | default("")

- name: Ensure configuration directory exists
  ansible.builtin.file:
    path: "{{ ulauncher_config_dir }}"
    state: directory
  become: false

- name: Create settings file
  ansible.builtin.copy:
    content: "{{ ulauncher_default_config | combine(ulauncher_config) | to_nice_json }}"
    dest: "{{ ulauncher_config_dir }}/settings.json"
  become: false
